### ISSUE TITLE
Can not import GPcounts

### ISSUE THREAD

**Issue by Giveyoucolorseesee** [ManchesterBioinference/GPcounts#19]
I followed your installation steps and ran "from GPcounts.GPcounts_Module import Fit_GPcounts",

It came up "ModuleNotFoundError: No module named 'GPcounts.GPcounts_Module'; 'GPcounts' is not a package"

**Comment by GreatDanPeng** [comment]
Hi, I run gpcounts successfully and you may use this conda dependency list:
```
# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: osx-arm64
absl-py=2.1.0=pypi_0
anndata=0.10.9=pypi_0
appnope=0.1.4=pyhd8ed1ab_1
array-api-compat=1.9.1=pypi_0
asttokens=3.0.0=pyhd8ed1ab_1
astunparse=1.6.3=pypi_0
backcall=0.2.0=pyh9f0ad1d_0
ca-certificates=2024.12.14=hf0a4a13_0
certifi=2024.12.14=pypi_0
charset-normalizer=3.4.0=pypi_0
check-shapes=1.1.1=pypi_0
cloudpickle=3.1.0=pypi_0
comm=0.2.2=pyhd8ed1ab_1
contourpy=1.3.0=pypi_0
cycler=0.12.1=pypi_0
debugpy=1.6.7=py39h313beb8_0
decorator=5.1.1=pyhd8ed1ab_1
deprecated=1.2.15=pypi_0
dm-tree=0.1.8=pypi_0
dropstackframe=0.1.0=pypi_0
entrypoints=0.4=pyhd8ed1ab_1
exceptiongroup=1.2.2=pypi_0
executing=2.1.0=pyhd8ed1ab_1
flatbuffers=24.3.25=pypi_0
fonttools=4.55.3=pypi_0
gast=0.6.0=pypi_0
get-annotations=0.1.2=pypi_0
google-pasta=0.2.0=pypi_0
gpflow=2.9.2=pypi_0
grpcio=1.68.1=pypi_0
h5py=3.12.1=pypi_0
idna=3.10=pypi_0
importlib-metadata=8.5.0=pypi_0
importlib-resources=6.4.5=pypi_0
ipykernel=6.29.5=pyh57ce528_0
ipython=8.12.0=pyhd1c38e8_0
jedi=0.19.2=pyhd8ed1ab_1
joblib=1.4.2=pypi_0
json-tricks=3.17.3=pypi_0
jug=2.3.1=pypi_0
jupyter_client=7.3.4=pyhd8ed1ab_0
jupyter_core=5.7.2=pyh31011fe_1
keras=3.7.0=pypi_0
kiwisolver=1.4.7=pypi_0
lark=1.2.2=pypi_0
legacy-api-wrap=1.4.1=pypi_0
libclang=18.1.1=pypi_0
libcxx=14.0.6=h848a8c0_0
libffi=3.4.4=hca03da5_1
libsodium=1.0.18=h27ca646_1
llvmlite=0.43.0=pypi_0
markdown=3.7=pypi_0
markdown-it-py=3.0.0=pypi_0
markupsafe=3.0.2=pypi_0
matplotlib=3.9.0=pypi_0
matplotlib-inline=0.1.7=pyhd8ed1ab_1
mdurl=0.1.2=pypi_0
ml-dtypes=0.4.1=pypi_0
multipledispatch=1.0.0=pypi_0
namex=0.0.8=pypi_0
natsort=8.4.0=pypi_0
ncurses=6.4=h313beb8_0
nest-asyncio=1.6.0=pyhd8ed1ab_1
networkx=3.2.1=pypi_0
numba=0.60.0=pypi_0
numpy=1.26.4=pypi_0
openssl=3.4.0=h39f12f2_0
opt-einsum=3.4.0=pypi_0
optree=0.13.1=pypi_0
packaging=24.2=pyhd8ed1ab_2
pandas=2.2.2=pypi_0
parso=0.8.4=pyhd8ed1ab_1
patsy=1.0.1=pypi_0
pexpect=4.9.0=pyhd8ed1ab_1
pickleshare=0.7.5=pyhd8ed1ab_1004
pillow=11.0.0=pypi_0
pip=24.2=py39hca03da5_0
platformdirs=4.3.6=pyhd8ed1ab_1
prompt-toolkit=3.0.48=pyha770c72_1
prompt_toolkit=3.0.48=hd8ed1ab_1
protobuf=4.25.5=pypi_0
psutil=5.9.0=py39h1a28f6b_0
ptyprocess=0.7.0=pyhd8ed1ab_1
pure_eval=0.2.3=pyhd8ed1ab_1
pygments=2.18.0=pyhd8ed1ab_1
pynndescent=0.5.13=pypi_0
pyparsing=3.2.0=pypi_0
python=3.9.21=hb885b13_1
python-dateutil=2.9.0.post0=pyhff2d567_1
python_abi=3.9=2_cp39
pytz=2024.2=pypi_0
pyzmq=25.1.2=py39h313beb8_0
readline=8.2=h1a28f6b_0
requests=2.32.3=pypi_0
rich=13.9.4=pypi_0
scanpy=1.10.1=pypi_0
scikit-learn=1.5.0=pypi_0
scipy=1.13.1=pypi_0
seaborn=0.13.2=pypi_0
session-info=1.0.0=pypi_0
setuptools=75.1.0=py39hca03da5_0
six=1.17.0=pyhd8ed1ab_0
sqlite=3.45.3=h80987f9_0
stack_data=0.6.3=pyhd8ed1ab_1
statsmodels=0.14.2=pypi_0
stdlib-list=0.11.0=pypi_0
tabulate=0.9.0=pypi_0
tensorboard=2.18.0=pypi_0
tensorboard-data-server=0.7.2=pypi_0
tensorflow=2.18.0=pypi_0
tensorflow-io-gcs-filesystem=0.37.1=pypi_0
tensorflow-macos=2.16.1=pypi_0
tensorflow-probability=0.25.0=pypi_0
termcolor=2.5.0=pypi_0
tf-keras=2.16.0=pypi_0
threadpoolctl=3.5.0=pypi_0
tk=8.6.14=h6ba3021_0
tornado=6.1=py39h5161555_1
tqdm=4.66.4=pypi_0
traitlets=5.14.3=pyhd8ed1ab_1
typing_extensions=4.12.2=pyha770c72_1
tzdata=2024.2=pypi_0
umap-learn=0.5.7=pypi_0
urllib3=2.2.3=pypi_0
wcwidth=0.2.13=pyhd8ed1ab_1
werkzeug=3.1.3=pypi_0
wheel=0.44.0=py39hca03da5_0
wrapt=1.17.0=pypi_0
xz=5.4.6=h80987f9_1
zeromq=4.3.5=h313beb8_0
zipp=3.21.0=pypi_0
zlib=1.2.13=h18a0788_1
```

**Comment by kinnaryshah** [comment]
Thanks @GreatDanPeng for this resource! I tried using your file to install, but am running into some incompatibility issues. I was wondering why you chose tensorflow==2.18.0 when the requirements.yml specifies tensorflow==2.16.1? Thanks!

**Comment by magnusrattray** [comment]
Hi all, we're aware of this issue and we are testing out a fix now, hopefully we can get a new version up soon [note: you can install an older 74437d9 commit (by running git checkout 74437d9 within the GPcounts folder) but it doesn't have some of the newer features for spatial transcriptomics].

**Comment by magnusrattray** [comment]
Hi, we've pushed an updated version which fixes the issue with versions and runs with the latest GPflow, tensorflow, python versions. I noticed that installing GPflow can lead to an older tensorflow version 2.16 being installed, if that happens you can run pip install -U tensorflow to get back up to vs 2.18. Let us know if you have any more issues.

**Comment by kinnaryshah** [comment]
Thank you so much for your prompt response! I was able to get this to run now. I also had to `pip install --upgrade tensorflow-probability` before installing GPcounts. I'm running [through](https://github.com/ManchesterBioinference/GPcounts/blob/master/demo_notebooks/GPcounts_spatial.ipynb) to check if all the functions are working, but am getting stuck on `results = gp_counts.calculate_FDR(log_likelihood_ratio)`. Is this working on your end? 

results = gp_counts.calculate_FDR(log_likelihood_ratio)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "GPcounts/GPcounts/RNA_seq_GP.py", line 396, in calculate_FDR
    genes_results["q_value"] = self.qvalue(genes_results["p_value"])
  File "GPcounts/GPcounts/RNA_seq_GP.py", line 449, in qvalue
    qv_temp = np.copy()
TypeError: copy() missing 1 required positional argument: 'a'

**Comment by magnusrattray** [comment]
Yes I also just confirmed that error - I need to check with @NuhaSaud and @sokratiag as I'm not familiar with this part (clearly an array needs to go in there as an argument). Hopefully they will reply soon.

**Comment by sokratiag** [comment]
Hi, I have fixed the errors - could you please pull the latest version and let us know if everything works as expected from your side? Thanks!

**Comment by kinnaryshah** [comment]
Thank you very much! Everything seems to be working now!

**Comment by sokratiag** [comment]
great, I will close this then!
